In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [4]:
data_path = '../input/data_v13.xlsx'
df = pd.read_excel(data_path)

In [3]:
# Item 5
data8 = df.copy()

def calculate_item_5(row):
    if pd.isna(row['Gender']) or pd.isna(row['BMI']) or pd.isna(row['FORCEPREHENSION']):
        return np.nan

    if row['Gender'] == 1:
        if row['BMI'] <= 24:
            cutoff = 29
        elif 24.1 <= row['BMI'] <= 26:
            cutoff = 30
        elif 24.1 <= row['BMI'] <= 28:
            cutoff = 30
        else:                       # row['BMI'] > 28
            cutoff = 32
    else:                           # Gender == 0
        if row['BMI'] <= 23:
            cutoff = 17
        elif 23.1 <= row['BMI'] <= 26:
            cutoff = 17.3
        elif 26.1 <= row['BMI'] <= 29:
            cutoff = 18
        else:                       # row['BMI'] > 29
            cutoff = 21

    return 1 if row['FORCEPREHENSION'] > cutoff else 0

data8['Item_5_grip'] = data8.apply(calculate_item_5, axis=1)
data8.head()

,Gender,VINCQ32DDN,VINICODEX003,FROPCOM0001,FROPCOM0005,FROPCOM0006_S1_,FROPCOM0006_S2_,FROPCOM0006_S3_,FROPCOM0006_S4_,FROPCOM0006_S5_,...,Item_4,Item_5,grip,Frailty_Score,Frailty_State,Fried_State,K_weight_loss,Item_1,Fried_Score,Item_5_grip
0,0,76.0,0.0,0.0,3.0,NaN,NaN,NaN,NaN,1.0,...,1.0,NaN,NaN,7,0,NaN,0.026316,0,NaN,0.0
1,0,75.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,21.5,4,1,1.0,0.000000,0,3.0,1.0
2,0,67.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,23.2,9,0,0.0,0.000000,0,2.0,1.0
3,0,72.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,17.7,7,0,0.0,-0.032787,0,2.0,1.0
4,1,69.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,40.0,8,0,0.0,0.000000,0,1.0,1.0

In [5]:
# 'Fried_Score' is the sum of the 5 items (Item_1, Item_2, Item_3, Item_4, Item_5). If one of the items is NaN, then the 'Fried_Score' is the sum of the other items.
data8 = df.copy()
data8['Fried_Score'] = data8[['Item_1', 'Item_2', 'Item_3', 'Item_4', 'Item_5']].dropna().sum(axis=1, min_count=1)
data8.head()

,Gender,VINCQ32DDN,VINICODEX003,FROPCOM0001,FROPCOM0005,FROPCOM0006_S1_,FROPCOM0006_S2_,FROPCOM0006_S3_,FROPCOM0006_S4_,FROPCOM0006_S5_,...,Item_3,Item_4,Frailty_Score,Frailty_State,K_weight_loss,Item_1,Item_5,Fried_Score,Fried_State,Auto_Evaluation
0,0,76.0,0.0,0.0,3.0,NaN,NaN,NaN,NaN,1.0,...,1.0,1.0,7,0,0.026316,0,0.0,3.0,1,10.0
1,0,75.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,4,1,0.000000,0,1.0,3.0,1,8.0
2,0,67.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,9,0,0.000000,0,1.0,2.0,0,9.0
3,0,72.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,7,0,-0.032787,0,1.0,2.0,0,10.0
4,1,69.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8,0,0.000000,0,1.0,1.0,0,9.0

In [7]:
# 'Fried_State' is 1 if 'Fried_Score' >= 3, else 0
data8['Fried_State_1'] = data8['Fried_Score'].apply(lambda x: 1 if x >= 3 else 0)
data8.head()

,Gender,VINCQ32DDN,VINICODEX003,FROPCOM0001,FROPCOM0005,FROPCOM0006_S1_,FROPCOM0006_S2_,FROPCOM0006_S3_,FROPCOM0006_S4_,FROPCOM0006_S5_,...,grip,Frailty_Score,Frailty_State,Fried_State,K_weight_loss,Item_1,Fried_Score,Item_5_grip,Fried_Score_1,Fried_State_1
0,0,76.0,0.0,0.0,3.0,NaN,NaN,NaN,NaN,1.0,...,NaN,7,0,NaN,0.026316,0,3.0,0.0,3.0,1
1,0,75.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,...,21.5,4,1,1.0,0.000000,0,3.0,1.0,3.0,1
2,0,67.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,23.2,9,0,0.0,0.000000,0,2.0,1.0,2.0,0
3,0,72.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,...,17.7,7,0,0.0,-0.032787,0,2.0,1.0,2.0,0
4,1,69.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.0,8,0,0.0,0.000000,0,1.0,1.0,1.0,0

In [8]:
# save to excel
#data8.to_excel('../input/data_v13.xlsx', index=False)